// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "openapi":"3.0.3",
    "info": {
      "title":"Gym Membership",
      "version":"1.0",
      "description": "Is documentation of API for Gym Membership capstone project by Group 10 MSIB B3"
    },
    "servers": [
        {
            "url":"http://ec2-3-85-131-211.compute-1.amazonaws.com/api/v1"
        }
    ],
    "paths": {
        "/auth/login": {
            "post": {
                "tags": ["Auth"],
                "summary": "Login user",
                "description": "Use an account is alredy registered/signup before, or use the superadmin account",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json":{
                            "schema":{
                                "type": "object",
                                "properties": {
                                    "email":{
                                        "type": "string",
                                        "minLength": 1,
                                        "format": "email",
                                        "required": ["true"]
                                    },
                                    "password":{
                                        "type": "string",
                                        "minLength": 6,
                                        "required": ["true"]
                                    }
                                }
                            },
                            "example": {
                                "email": "james@gmail.com",
                                "password": "james123"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Login success",
                        "content": {
                            "application/json":{
                                "schema":{
                                    "type":"object",
                                    "properties": {
                                        "message":{
                                            "type": "string"
                                        },
                                        "data":{
                                            "type": "object",
                                            "properties": {
                                                "access_token":{
                                                    "type": "string",
                                                    "format": "jwt"
                                                },
                                                "refresh_token":{
                                                    "type": "string",
                                                    "format": "jwt"
                                                }
                                            }
                                        }
                                    }
                                },
                                "example": {
                                    "message": "login success",
                                    "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsInJvbGUiOjB9.7W8I-3lyZ1X_a27VBNWHSH5yULLrf_GC8vRd2dyMOsg",
                                    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsInJvbGUiOjB9.7W8I-3lyZ1X_a27VBNWHSH5yULLrf_GC8vRd2dyMOsg"
                                }
                            }
                        }
                    },
                    "400":{
                        "$ref": "#/components/responses/badRequest"
                    },
                    "500": {
                        "$ref": "#/components/responses/internalServerError"
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "tags": ["Auth"],
                "summary": "User Logout",
                "description": "User logout remove the session id",
                "responses": {
                    "200": {
                        "description": "Login success",
                        "content": {
                            "application/json":{
                                "schema":{
                                    "type":"object",
                                    "properties": {
                                        "message":{
                                            "type": "string"
                                        },
                                        "data":{
                                            "type": "object",
                                            "properties": {
                                                "access_token":{
                                                    "type": "string",
                                                    "format": "jwt token"
                                                },
                                                "refresh_token":{
                                                    "type": "string",
                                                    "format": "jwt token"
                                                }
                                            }
                                        }
                                    }
                                },
                                "example": {
                                    "message": "login success",
                                    "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsInJvbGUiOjB9.7W8I-3lyZ1X_a27VBNWHSH5yULLrf_GC8vRd2dyMOsg",
                                    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsInJvbGUiOjB9.7W8I-3lyZ1X_a27VBNWHSH5yULLrf_GC8vRd2dyMOsg"
                                }
                            }
                        }
                    },
                    "400":{
                        "$ref": "#/components/responses/badRequest"
                    },
                    "500": {
                        "$ref": "#/components/responses/internalServerError"
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "tags": ["Auth"],
                "summary": "Generate new token",
                "description": "When access_token is expired use refresh_token to generate the new token",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json":{
                            "schema":{
                                "type": "object",
                                "properties": {
                                    "refresh_token":{
                                        "type": "string",
                                        "minLength": 1,
                                        "format": "jwt token",
                                        "required": ["true"]
                                    }
                                }
                            },
                            "example": {
                                "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsInJvbGUiOjB9.7W8I-3lyZ1X_a27VBNWHSH5yULLrf_GC8vRd2dyMOsg"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success generate new token",
                        "content": {
                            "application/json":{
                                "schema":{
                                    "type":"object",
                                    "properties": {
                                        "message":{
                                            "type": "string"
                                        },
                                        "data":{
                                            "type": "object",
                                            "properties": {
                                                "access_token":{
                                                    "type": "string",
                                                    "format": "jwt token"
                                                },
                                                "refresh_token":{
                                                    "type": "string",
                                                    "format": "jwt token"
                                                }
                                            }
                                        }
                                    }
                                },
                                "example": {
                                    "message": "success refresh token",
                                    "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsInJvbGUiOjB9.7W8I-3lyZ1X_a27VBNWHSH5yULLrf_GC8vRd2dyMOsg",
                                    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsInJvbGUiOjB9.7W8I-3lyZ1X_a27VBNWHSH5yULLrf_GC8vRd2dyMOsg"
                                }
                            }
                        }
                    },
                    "400":{
                        "$ref": "#/components/responses/badRequest"
                    },
                    "500": {
                        "$ref": "#/components/responses/internalServerError"
                    },
                    "401" :{
                        "$ref": "#/components/responses/unauthorized"
                    }
                }
            }
        },
        "/users/signup": {
            "post": {
                "tags": ["Users"],
                "summary": "Signup new user",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json":{
                            "schema":{
                                "type": "object",
                                "properties": {
                                    "name":{
                                        "type": "string",
                                        "minLength": 1,
                                        "required": ["true"]
                                    },
                                    "email":{
                                        "type": "string",
                                        "minLength": 1,
                                        "format": "email",
                                        "required": ["true"]
                                    },
                                    "password":{
                                        "type": "string",
                                        "minLength": 6,
                                        "required": ["true"]
                                    }
                                }
                            },
                            "example": {
                                "name": "James",
                                "email": "james@gmail.com",
                                "password": "james123"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success signup",
                        "content": {
                            "application/json":{
                                "schema":{
                                    "type":"object",
                                    "properties": {
                                        "message":{
                                            "type": "string"
                                        }
                                    }
                                },
                                "example": {
                                    "message": "signup success"
                                }
                            }
                        }
                    },
                    "400":{
                       "$ref": "#/components/responses/badRequest"
                    },
                    "500":{
                        "$ref": "#/components/responses/internalServerError"
                    }
                }
            }
        },
        "/users/profile": {
            "get": {
                "security": [
                    {
                        "AccessToken":[]
                    }
                ],
                "tags": ["Users"],
                "summary": "Get the user profile",
                "description": "To get the user profile",
                "responses": {
                    "200": {
                        "description": "Success get profile",
                        "content": {
                            "application/json":{
                                "schema": {
                                    "$ref": "#/components/schemas/user"
                                },
                                "example": {
                                    "message": "success get profile",
                                    "data": {
                                        "name":"james",
                                        "email":"james@gmail.com",
                                        "role":"user"
                                    }
                                }
                            }
                        }
                    },
                    "500":{
                        "$ref": "#/components/responses/internalServerError"
                    },
                    "401":{
                        "$ref": "#/components/responses/unauthorized"
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "AccessToken":[]
                    }
                ],
                "parameters": [
                    {
                        "$ref": "#/components/parameters/page"
                    },
                    {
                        "$ref": "#/components/parameters/limit"
                    },
                    {
                        "$ref": "#/components/parameters/q"
                    }
                ],
                "tags": ["Users"],
                "summary": "Get all users",
                "description": "To get all users and only admin account can get all users",
                "responses": {
                    "200": {
                        "description": "Success get users",
                        "content": {
                            "application/json":{
                                "schema":{
                                    "type":"object",
                                    "properties": {
                                        "message":{
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "users": {
                                                    "type": "array",
                                                    "items":{
                                                        "type": "object",
                                                        "properties": {
                                                            "id": {
                                                                "type": "number"
                                                            },
                                                            "name": {
                                                                "type": "string"
                                                            },
                                                            "email": {
                                                                "type": "string"
                                                            }
                                                        }
                                                    }
                                                },
                                                "count": {
                                                    "type": "integer"
                                                }
                                            }
                                        }
                                    }
                                },
                                "example": {
                                    "message": "success get profile",
                                    "data": {
                                        "users": [
                                            {
                                                "id": 2,
                                                "name": "james",
                                                "email": "james@gmail.com"
                                            },
                                            {
                                                "id": 3,
                                                "name": "yanto",
                                                "email": "yanto@gmail.com"
                                            }
                                        ],
                                        "count": 2
                                    }
                                }
                            }
                        }
                    },
                    "500":{
                        "$ref": "#/components/responses/internalServerError"
                    },
                    "401":{
                        "$ref": "#/components/responses/unauthorized"
                    },
                    "403":{
                        "$ref": "#/components/responses/forbidden"
                    }
                }
            }
        },
        "/classes/offline": {
            "get": {
                "security": [
                    {
                        "AccessToken":[]
                    }
                ],
                "parameters": [
                    {
                        "$ref": "#/components/parameters/page"
                    },
                    {
                        "$ref": "#/components/parameters/limit"
                    },
                    {
                        "$ref": "#/components/parameters/q"
                    }
                ],
                "tags": ["Offline Classes"],
                "summary": "Get all offline classes",
                "description": "To get all offline classes",
                "responses": {
                    "200": {
                        "description": "Success get offline classes",
                        "content": {
                            "application/json":{
                                "schema":{
                                    "type":"object",
                                    "properties": {
                                        "message":{
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "offline_classes": {
                                                    "type": "array",
                                                    "items":{
                                                        "type": "object",
                                                        "properties": {
                                                            "id":{
                                                                "type": "string",
                                                                "format": "UUID"
                                                            },
                                                            "title":{
                                                                "type":"string"
                                                            },
                                                            "time":{
                                                                "type":"string",
                                                                "description": "use time format"
                                                            },
                                                            "duration":{
                                                                "type": "integer",
                                                                "description": "format minutes"
                                                            },
                                                            "slot":{
                                                                "type": "integer"
                                                            },
                                                            "slot_ready":{
                                                                "type": "integer",
                                                                "description": "remaining slots"
                                                            },
                                                            "price": {
                                                                "type": "integer"
                                                            },
                                                            "picture_path":{
                                                                "type": "string",
                                                                "description": "dispay picture fo the class"
                                                            },
                                                            "trainer_id":{
                                                                "type": "string",
                                                                "format": "UUID"
                                                            },
                                                            "description":{
                                                                "type": "string",
                                                                "description": "more information about the class"
                                                            }
                                                        }
                                                    }
                                                },
                                                "count": {
                                                    "type": "integer"
                                                }
                                            }
                                        }
                                    }
                                },
                                "example": {
                                    "message": "success get offline classes",
                                    "data": {
                                        "offline_classes": [
                                            {
                                                "id":"123e4567-e89b-12d3-a456-4266141711111",
                                                "title": "Zumba Internasional Class",
                                                "time": "2012-10-31 15:50:13.793654 +0000 UTC",
                                                "duration": 60,
                                                "slot": 50,
                                                "slot_ready": 34,
                                                "price": 500000,
                                                "picture_path": "http://gambar.com/offlineClass/123e4567-e89b-12d3-a456-426614174111.jpg",
                                                "trainer_id": "123e4567-e89b-12d3-a456-426614174000",
                                                "description": "offline class zumba tingkat internasional"
                                            },
                                            {
                                                "id":"123e4567-e89b-12d3-a456-4266141711112",
                                                "title": "Zumba Internasional Class",
                                                "time": "2012-10-31 15:50:13.793654 +0000 UTC",
                                                "duration": 60,
                                                "slot": 50,
                                                "slot_ready": 34,
                                                "price": 500000,
                                                "picture_path": "http://gambar.com/offlineClass/123e4567-e89b-12d3-a456-426614174111.jpg",
                                                "trainer_id": "123e4567-e89b-12d3-a456-426614174000",
                                                "description": "offline class zumba tingkat internasional"
                                            }
                                        ],
                                        "count": 2
                                    }
                                }
                            }
                        }
                    },
                    "500":{
                        "$ref": "#/components/responses/internalServerError"
                    },
                    "401":{
                        "$ref": "#/components/responses/unauthorized"
                    },
                    "403":{
                        "$ref": "#/components/responses/forbidden"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AccessToken":[]
                    }
                ],
                "tags": ["Offline Classes"],
                "summary": "New offline class",
                "description": "To create new offline class",
                "requestBody":{
                    "required": true,
                    "content": {
                        "application/json":{
                            "schema":{
                                "$ref": "#/components/schemas/offlineClass"
                            },
                            "example":{
                                "title": "Zumba Internasional Class",
                                "time": "2012-10-31 15:50:13.793654 +0000 UTC",
                                "duration": 60,
                                "slot": 50,
                                "slot_ready": 34,
                                "price": 500000,
                                "picture_path": "http://gambar.com/offlineClass/123e4567-e89b-12d3-a456-426614174111.jpg",
                                "trainer_id": "123e4567-e89b-12d3-a456-426614174000",
                                "description": "offline class zumba tingkat internasional"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success create offline class",
                        "content": {
                            "application/json":{
                                "schema":{
                                    "type":"object",
                                    "properties": {
                                        "message":{
                                            "type": "string"
                                        }
                                    }
                                },
                                "example": {
                                    "message": "success create offline class"
                                }
                            }
                        }
                    },
                    "400":{
                        "$ref": "#/components/responses/badRequest"
                    },
                    "500":{
                        "$ref": "#/components/responses/internalServerError"
                    },
                    "401":{
                        "$ref": "#/components/responses/unauthorized"
                    },
                    "403":{
                        "$ref": "#/components/responses/forbidden"
                    }
                }
            }
        },
        "/classes/offline/{id}":{
            "get": {
                "security": [
                    {
                        "AccessToken":[]
                    }
                ],
                "parameters": [
                    {
                        "$ref": "#/components/parameters/id"
                    }
                ],
                "tags": ["Offline Classes"],
                "summary": "Get single offline class",
                "description": "To get spesific offline class",
                "responses": {
                    "200": {
                        "description": "Success get offline class",
                        "content": {
                            "application/json":{
                                "schema":{
                                    "type":"object",
                                    "properties": {
                                        "message":{
                                            "type": "string"
                                        },
                                        "data":{
                                            "type": "object",
                                            "properties": {
                                                "id":{
                                                    "type":"string",
                                                    "format": "UUID"
                                                },
                                                "title":{
                                                    "type":"string"
                                                },
                                                "time":{
                                                    "type":"string",
                                                    "description": "use time format"
                                                },
                                                "duration":{
                                                    "type": "integer",
                                                    "description": "format minutes"
                                                },
                                                "slot":{
                                                    "type": "integer"
                                                },
                                                "slot_ready":{
                                                    "type": "integer",
                                                    "description": "remaining slots"
                                                },
                                                "price": {
                                                    "type": "integer"
                                                },
                                                "picture_path":{
                                                    "type": "string",
                                                    "description": "dispay picture fo the class"
                                                },
                                                "trainer_id":{
                                                    "type": "string",
                                                    "format": "UUID"
                                                },
                                                "description":{
                                                    "type": "string",
                                                    "description": "more information about the class"
                                                }
                                            }
                                        }
                                    }
                                },
                                "example": {
                                    "message": "success get offline class",
                                    "data": {
                                        "id": "123e4567-e89b-12d3-a456-4266141711111",
                                        "title": "Zumba Internasional Class",
                                        "time": "2012-10-31 15:50:13.793654 +0000 UTC",
                                        "duration": 60,
                                        "slot": 50,
                                        "slot_ready": 34,
                                        "price": 500000,
                                        "picture_path": "http://gambar.com/offlineClass/123e4567-e89b-12d3-a456-426614174111.jpg",
                                        "trainer_id": "123e4567-e89b-12d3-a456-426614174000",
                                        "description": "offline class zumba tingkat internasional"
                                    }
                                }
                            }
                        }
                    },
                    "404":{
                        "$ref": "#/components/responses/notFound"
                    },
                    "500":{
                        "$ref": "#/components/responses/internalServerError"
                    },
                    "401":{
                        "$ref": "#/components/responses/unauthorized"
                    },
                    "403":{
                        "$ref": "#/components/responses/forbidden"
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "AccessToken":[]
                    }
                ],
                "parameters": [
                    {
                        "$ref": "#/components/parameters/id"
                    }
                ],
                "tags": ["Offline Classes"],
                "summary": "Update offline class",
                "description": "To update offline classs",
                "requestBody":{
                    "required": true,
                    "content": {
                        "application/json":{
                            "schema":{
                                "$ref": "#/components/schemas/offlineClass"
                            },
                            "example": {
                                "title": "Zumba Internasional Class",
                                "time": "2012-10-31 15:50:13.793654 +0000 UTC",
                                "duration": 60,
                                "slot": 50,
                                "slot_ready": 34,
                                "price": 500000,
                                "picture_path": "http://gambar.com/offlineClass/123e4567-e89b-12d3-a456-426614174111.jpg",
                                "trainer_id": "123e4567-e89b-12d3-a456-426614174000",
                                "description": "offline class zumba tingkat internasional"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success update offline class",
                        "content": {
                            "application/json":{
                                "schema":{
                                    "type":"object",
                                    "properties": {
                                        "message":{
                                            "type": "string"
                                        }
                                    }
                                },
                                "example": {
                                    "message": "success update offline class"
                                }
                            }
                        }
                    },
                    "404":{
                        "$ref": "#/components/responses/notFound"
                    },
                    "500":{
                        "$ref": "#/components/responses/internalServerError"
                    },
                    "401":{
                        "$ref": "#/components/responses/unauthorized"
                    },
                    "403":{
                        "$ref": "#/components/responses/forbidden"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "AccessToken":[]
                    }
                ],
                "parameters": [
                    {
                        "$ref": "#/components/parameters/id"
                    }
                ],
                "tags": ["Offline Classes"],
                "summary": "Delete offline classes",
                "description": "To delete offline classes use the the id",
                "responses": {
                    "200": {
                        "description": "Success delete offline calss",
                        "content": {
                            "application/json":{
                                "schema":{
                                    "type":"object",
                                    "properties": {
                                        "message":{
                                            "type": "string"
                                        }
                                    }
                                },
                                "example": {
                                    "message": "success delete offline class"
                                }
                            }
                        }
                    },
                    "404": {
                        "$ref":"#/components/responses/notFound"
                    },
                    "500":{
                        "$ref": "#/components/responses/internalServerError"
                    },
                    "401":{
                        "$ref": "#/components/responses/unauthorized"
                    },
                    "403":{
                        "$ref": "#/components/responses/forbidden"
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "AccessToken":{
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        },
        "schemas": {
            "user":{
                "type":"object",
                "properties": {
                    "message":{
                        "type": "string"
                    },
                    "data": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "email": {
                                "type": "string"
                            },
                            "role":{
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "offlineClass": {
                "type": "object",
                "properties": {
                    "title":{
                        "type":"string"
                    },
                    "time":{
                        "type":"string",
                        "description": "use time format"
                    },
                    "duration":{
                        "type": "integer",
                        "description": "format minutes"
                    },
                    "slot":{
                        "type": "integer"
                    },
                    "slot_ready":{
                        "type": "integer",
                        "description": "remaining slots"
                    },
                    "price": {
                        "type": "integer"
                    },
                    "picture_path":{
                        "type": "string",
                        "description": "dispay picture fo the class"
                    },
                    "trainer_id":{
                        "type": "string",
                        "format": "UUID"
                    },
                    "description":{
                        "type": "string",
                        "description": "more information about the class"
                    }
                }
            }
        },
        "responses": {
            "badRequest":{
                "description": "Badrequest body",
                "content": {
                    "application/json":{
                        "schema":{
                            "type":"object",
                            "properties": {
                                "message":{
                                    "type": "string"
                                }
                            }
                        },
                        "example": {
                            "message": "bad request body"
                        }
                    }
                }
            },
            "notFound":{
                "description": "Not found",
                "content": {
                    "application/json":{
                        "schema":{
                            "type":"object",
                            "properties": {
                                "message":{
                                    "type": "string"
                                }
                            }
                        },
                        "example": {
                            "message": "not found"
                        }
                    }
                }
            },
            "internalServerError":{
                "description": "Internal server error",
                "content": {
                    "application/json":{
                        "schema":{
                            "type":"object",
                            "properties": {
                                "message":{
                                    "type": "string"
                                }
                            }
                        },
                        "example": {
                            "message": "internal server error"
                        }
                    }
                }
            },
            "forbidden":{
                "description": "Forbidden",
                "content": {
                    "application/json":{
                        "schema":{
                            "type":"object",
                            "properties": {
                                "message":{
                                    "type": "string"
                                }
                            }
                        },
                        "example": {
                            "message": "forbidden"
                        }
                    }
                }
            },
            "unauthorized":{
                "description": "Unauthorized",
                "content": {
                    "application/json":{
                        "schema":{
                            "type":"object",
                            "properties": {
                                "message":{
                                    "type": "string"
                                }
                            }
                        },
                        "example": {
                            "message": "unauthorized"
                        }
                    }
                }
            }
        },
        "parameters": {
            "page": {
                "in": "query",
                "name": "page",
                "schema":{
                    "type": "integer",
                    "description": "The number of page (page)"
                },
                "example": 1
            },
            "limit": {
                "in": "query",
                "name": "limit",
                "schema": {
                    "type": "integer",
                    "description": "The numbers of items to return (per page)"
                },
                "example": 10
            },
            "q": {
                "in": "query",
                "name": "q",
                "schema": {
                    "type": "string",
                    "description": "Search field of name or email user"
                },
                "example": "james"
            },
            "id": {
                "required": true,
                "in": "path",
                "name": "id",
                "schema": {
                    "type": "string",
                    "description": "The spesific id for the operation"
                },
                "example": "123e4567-e89b-12d3-a456-426614174000"
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
